blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:pk>', views.blog_detail, name='blog_detail'),
    path('<category>', views.blog_category, name='blog_category'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_index, name='home_index'),
]

sta_website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('news', include('news.urls')),
    path('blog/', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

class Welcome(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50]

    class Meta:
        verbose_name_plural = 'Welcome'

class Testimonial(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    welcome = models.ForeignKey('Welcome', on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ' ' + self.text[:50]

home/views.py
from django.shortcuts import render
from django.contrib import messages
from home.models import Welcome, Testimonial
from blog.models import Post
from about.models import Biography

# Create your views here.

def home_index(request):
    welcome = Welcome.objects.all()[:1]
    testimonial = Testimonial.objects.all()
    recent_posts = Post.objects.all().order_by('-created_on')[:3]
    bios = Biography.objects.all()
    context = {
        'welcome' : welcome,
        'testimonial' : testimonial,
        'recent_posts': recent_posts,
        'bios': bios,
    }

    messages.info(request, 'Please pardon our appearance, this page is under construction.')

    return render(request, 'index.html', context)

home/templates/index.html
{% extends "base.html" %}

{% block page_content %}

<section class="destination" id="welcome" name="welcome"></section>
{% comment %} <h2>Home</h2> {% endcomment %}
<div class="container">
    <div class="jumbotron">
        {% with welcome|first as welcome %}
            <h3> {{ welcome.text|safe|linebreaks }} </h3>
        {% endwith%}
    </div>
    <hr>
</div>

<section class="destination" id="testimonials" name="testimonials"></section>

<div class="container">
    <h2>Real Customers, Real Reviews</h2>
    <div class="jumbotron">
        {% with welcome|first as welcome %}
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="5000">
        <ol class="carousel-indicators">
            {% for t in welcome.testimonial_set.all %}
                {% if forloop.first %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                {% else %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="forloop.counter"></li>
                {% endif %}
            {% endfor %}
        </ol>
        <div class="carousel-inner">
            {% for t in welcome.testimonial_set.all %}
                {% if forloop.first %}
                    <div class="carousel-item active">
                {% else %}
                    <div class="carousel-item">
                {% endif %}
                    <blockquote class="blockquote">
                        <p>{{ t.text }}</p>
                        <footer class="blockquote-footer">{{ t.name }}</footer>
                    </blockquote>
                </div>
            {% endfor %}
        </div>
        </div>
        {% endwith %}
    </div>
</div>

{% endblock %}